### PR TITLE
add github stats chart at main page

### PR DESCRIPTION
**Pull request by ryanviana**
#6 

## Description

Creates a batch 4 github stats chart for the main page, following the style of check in chart.

image

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: 0xF3b64dD5AF39d8fF0c614F7637e339e31466c4C3

### CODE REVIEW

**Review by BillSchumacher — APPROVED** [review]
🔥

**Review by carletex — CHANGES_REQUESTED** [review]
Love this @ryanviana !

Left a couple of tiny comments.

Also an optional suggestion: since we are using `react-chartjs`, maybe we could use a better chart for this one. I'm not a data visualization guy, but the X axis is usually things like time, right? Maybe there is a better chart to represent this (forks, start, etc)?

Maybe https://react-chartjs-2.js.org/examples/horizontal-bar-chart/??

IDK, thinking out loud. Feel free to ignore tho :P

**Comment by ryanviana** [comment]
Great comments, @carletex! I reviewed the code, updated the image in the description, and pushed some commits ;)

**Comment by carletex** [comment]
Good stuff @ryanviana !

**Pull request merged**
