### PR TITLE
Added checked in builders count in the homepage

### PR DESCRIPTION
**Pull request by yashgo0018**
## Description
Screenshot from 2024-04-09 09-36-43

Added the checked in builders count in the homepage.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #5_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: buidlguidl.yashgoyal.eth

### CODE REVIEW

**Review by BillSchumacher — APPROVED** [review]
LGTM

**Review by envilogger — APPROVED** [review]

**Review by carletex — CHANGES_REQUESTED** [review]
Thanks for this @yashgo0018 !

It's working correctly, but I'd suggest implementing a loader. If not it shows a 0 until the data loads. You can check:

- Props returning from `useScaffoldContractRead`
- The DaisyUI spinner https://daisyui.com/components/loading/

**Comment by yashgo0018** [comment]
Added a loader

**Review by bhavyagor12 — APPROVED** [review]
LGTM!

**Comment by carletex** [comment]
Looking great!!

**Pull request merged**
